'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BaseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BaseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Conceptos() As DbSet(Of Conceptos)
    Public Property Estatus() As DbSet(Of Estatus)
    Public Property Parametros() As DbSet(Of Parametros)
    Public Property Usuarios() As DbSet(Of Usuarios)
    Public Property webpages_Membership() As DbSet(Of webpages_Membership)
    Public Property webpages_Roles() As DbSet(Of webpages_Roles)
    Public Property webpages_Acciones() As DbSet(Of webpages_Acciones)
    Public Property Ruta() As DbSet(Of Ruta)
    Public Property RutaCheckpoint() As DbSet(Of RutaCheckpoint)
    Public Property Grupo() As DbSet(Of Grupo)
    Public Property CheckIn() As DbSet(Of CheckIn)
    Public Property Forma() As DbSet(Of Forma)
    Public Property FormaPregunta() As DbSet(Of FormaPregunta)
    Public Property FormaPreguntaOpcion() As DbSet(Of FormaPreguntaOpcion)
    Public Property Conversacion() As DbSet(Of Conversacion)
    Public Property Mensaje() As DbSet(Of Mensaje)
    Public Property VistaGrupo() As DbSet(Of VistaGrupo)
    Public Property FormaRespuesta() As DbSet(Of FormaRespuesta)
    Public Property FormaRespuestaDetalle() As DbSet(Of FormaRespuestaDetalle)
    Public Property FormaRespuestaDetalle2() As DbSet(Of FormaRespuestaDetalle2)
    Public Property TipoNoticia() As DbSet(Of TipoNoticia)
    Public Property Noticias() As DbSet(Of Noticias)
    Public Property CapacitacionTema() As DbSet(Of CapacitacionTema)
    Public Property CapacitacionVisitas() As DbSet(Of CapacitacionVisitas)
    Public Property CapacitacionArchivos() As DbSet(Of CapacitacionArchivos)
    Public Property Capacitacion() As DbSet(Of Capacitacion)
    Public Property Notificaciones() As DbSet(Of Notificaciones)
    Public Property Cliente() As DbSet(Of Cliente)
    Public Property Producto() As DbSet(Of Producto)
    Public Property UsuariosAcceso() As DbSet(Of UsuariosAcceso)

End Class
