'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Capacitacion
    Public Property idCapacitacion As Integer
    Public Property NombreCapacitacion As String
    Public Property Descripcion As String
    Public Property FechaInicio As Date
    Public Property FechaFin As Date
    Public Property Activo As Boolean

    Public Overridable Property CapacitacionTema As ICollection(Of CapacitacionTema) = New HashSet(Of CapacitacionTema)
    Public Overridable Property Grupo As ICollection(Of Grupo) = New HashSet(Of Grupo)

End Class
