'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CapacitacionTema
    Public Property idTemaCapacitacion As Integer
    Public Property idCapacitacion As Integer
    Public Property Titulo As String
    Public Property Descripcion As String
    Public Property Orden As Integer

    Public Overridable Property Capacitacion As Capacitacion
    Public Overridable Property CapacitacionArchivos As ICollection(Of CapacitacionArchivos) = New HashSet(Of CapacitacionArchivos)

End Class
