'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CapacitacionArchivos
    Public Property idCapacitacionArchivos As Integer
    Public Property idTemaCapacitacion As Integer
    Public Property Titulo As String
    Public Property Descripcion As String
    Public Property URL As String
    Public Property Orden As Integer

    Public Overridable Property CapacitacionVisitas As ICollection(Of CapacitacionVisitas) = New HashSet(Of CapacitacionVisitas)
    Public Overridable Property CapacitacionTema As CapacitacionTema

End Class
