'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class CheckIn
    Public Property idCheckin As Integer
    Public Property idUsuario As Integer
    Public Property idCheckpoint As Integer
    Public Property Latitud As Double
    Public Property Longitud As Double
    Public Property Fecha As Date
    Public Property EsEntrada As Boolean

    <JsonIgnore>
    Public Overridable Property RutaCheckpoint As RutaCheckpoint
    <JsonIgnore>
    Public Overridable Property Usuarios As Usuarios

End Class
