'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property idCliente As Integer
    Public Property NombreCliente As String
    Public Property Logo As String
    Public Property Activo As Boolean

    Public Overridable Property Forma As ICollection(Of Forma) = New HashSet(Of Forma)
    Public Overridable Property Grupo As ICollection(Of Grupo) = New HashSet(Of Grupo)
    Public Overridable Property Producto As ICollection(Of Producto) = New HashSet(Of Producto)
    Public Overridable Property Ruta As ICollection(Of Ruta) = New HashSet(Of Ruta)
    Public Overridable Property UsuariosAcceso As ICollection(Of UsuariosAcceso) = New HashSet(Of UsuariosAcceso)

End Class
