'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Conversacion
    Public Property idConversacion As Integer
    Public Property FechaCreacion As Date
    Public Property idUsuario As Integer
    Public Property idUsuarioInvitado As Nullable(Of Integer)
    Public Property Nombre As String
    Public Property Grupal As Boolean
    Public Property UltimoMensaje As String
    Public Property UltimoFecha As Nullable(Of Date)

    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property Usuarios1 As Usuarios
    Public Overridable Property Mensaje As ICollection(Of Mensaje) = New HashSet(Of Mensaje)
    Public Overridable Property Usuarios2 As ICollection(Of Usuarios) = New HashSet(Of Usuarios)

End Class
