'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Estatus
    Public Property idEstatus As Integer
    Public Property idConcepto As Integer
    Public Property ClaveInterna As String
    Public Property ClaveExterna As String
    Public Property Descripcion As String

    Public Overridable Property Conceptos As Conceptos

End Class
