'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class FormaPreguntaOpcion
    Public Property idFormaPreguntaOpcion As Integer
    Public Property idFormaPregunta As Integer
    Public Property Opcion As String

    <JsonIgnore>
    Public Overridable Property FormaPregunta As FormaPregunta
    <JsonIgnore>
    Public Overridable Property FormaRespuestaDetalle As ICollection(Of FormaRespuestaDetalle) = New HashSet(Of FormaRespuestaDetalle)
    <JsonIgnore>
    Public Overridable Property FormaRespuestaDetalle2 As ICollection(Of FormaRespuestaDetalle2) = New HashSet(Of FormaRespuestaDetalle2)

End Class
