'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class FormaRespuesta
    Public Property idFormaRespuesta As Integer
    Public Property idForma As Integer
    Public Property idUsuario As Integer
    Public Property FechaInicio As Date
    Public Property FechaFin As Date
    Public Property idRutaCheckpoint As Integer

    <JsonIgnore>
    Public Overridable Property Forma As Forma
    Public Overridable Property RutaCheckpoint As RutaCheckpoint
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property FormaRespuestaDetalle As ICollection(Of FormaRespuestaDetalle) = New HashSet(Of FormaRespuestaDetalle)
    Public Overridable Property FormaRespuestaDetalle2 As ICollection(Of FormaRespuestaDetalle2) = New HashSet(Of FormaRespuestaDetalle2)

End Class
