'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class FormaRespuestaDetalle
    Public Property idFormaRespuesta As Integer
    Public Property idFormaPregunta As Integer
    Public Property idFormaPreguntaOpcion As Nullable(Of Integer)
    Public Property Respuesta As String

    <JsonIgnore>
    Public Overridable Property FormaPregunta As FormaPregunta
    <JsonIgnore>
    Public Overridable Property FormaPreguntaOpcion As FormaPreguntaOpcion
    <JsonIgnore>
    Public Overridable Property FormaRespuesta As FormaRespuesta

End Class
