'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class Grupo
    Public Property idGrupo As Integer
    Public Property Descripcion As String
    Public Property idProducto As Integer
    Public Property idCliente As Integer

    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)
    <JsonIgnore>
    Public Overridable Property Ruta As ICollection(Of Ruta) = New HashSet(Of Ruta)
    <JsonIgnore>
    Public Overridable Property Capacitacion As ICollection(Of Capacitacion) = New HashSet(Of Capacitacion)
    <JsonIgnore>
	Public Overridable Property Cliente As Cliente
    <JsonIgnore>
	Public Overridable Property Producto As Producto
    <JsonIgnore>
	Public Overridable Property Noticias As ICollection(Of Noticias) = New HashSet(Of Noticias)

End Class
