'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class Mensaje
    Public Property idMensaje As Integer
    Public Property idConversacion As Integer
    Public Property idUsuario As Integer
    Public Property Mensaje1 As String
    Public Property FechaCreacion As Date
    Public Property FechaVisto As Nullable(Of Date)
    Public Property Visto As Boolean

    <JsonIgnore>
    Public Overridable Property Conversacion As Conversacion
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property VistaGrupo As ICollection(Of VistaGrupo) = New HashSet(Of VistaGrupo)

End Class
