'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Noticias
    Public Property idNoticia As Integer
    Public Property Titulo As String
    Public Property Mensaje As String
    Public Property FechaInicio As Date
    Public Property FechaFin As Date
    Public Property Imagen As String
    Public Property idTipoNoticia As String
    Public Property Activa As Boolean

    Public Overridable Property TipoNoticia As TipoNoticia
    Public Overridable Property Grupo As ICollection(Of Grupo) = New HashSet(Of Grupo)

End Class
