'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Notificaciones
    Public Property idNotificacion As Integer
    Public Property Mensaje As String
    Public Property Fecha As Date
    Public Property idUsuario As Integer

    Public Overridable Property Usuarios As Usuarios

End Class
