'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class Ruta
    Public Property idRuta As Integer
    Public Property Descripcion As String
    Public Property idProducto As Integer
    Public Property idCliente As Integer

    Public Overridable Property RutaCheckpoint As ICollection(Of RutaCheckpoint) = New HashSet(Of RutaCheckpoint)
    <JsonIgnore>
    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)
    <JsonIgnore>
    Public Overridable Property Grupo As ICollection(Of Grupo) = New HashSet(Of Grupo)

    Public Overridable Property Forma As ICollection(Of Forma) = New HashSet(Of Forma)
    <JsonIgnore>
    Public Overridable Property Cliente As Cliente
    <JsonIgnore>
    Public Overridable Property Producto As Producto

End Class
