'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json

Partial Public Class RutaCheckpoint
    Public Property idRutaCheckPoint As Integer
    Public Property idRuta As Integer
    Public Property Latitud As Double
    Public Property Longitud As Double
    Public Property Lugar As String
    Public Property Descripcion As String
    Public Property Llegada As Date
    Public Property Salida As Date

    <JsonIgnore>
    Public Overridable Property Ruta As Ruta
    <JsonIgnore>
    Public Overridable Property CheckIn As ICollection(Of CheckIn) = New HashSet(Of CheckIn)
    <JsonIgnore>
    Public Overridable Property FormaRespuesta As ICollection(Of FormaRespuesta) = New HashSet(Of FormaRespuesta)

End Class
