'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports Newtonsoft.Json
Imports System.ComponentModel.DataAnnotations

Partial Public Class Usuarios
    Public Property idUsuario As Integer
    Public Property Nombre As String
    Public Property Correo As String
    <Display(name:="Información de Contacto")>
    Public Property InformacionContacto As String
    <Display(name:="Cuenta Activa")>
    Public Property CuentaActiva As Boolean
    Public Property PlayerId As String

    <JsonIgnore>
    Public Overridable Property webpages_Roles As ICollection(Of webpages_Roles) = New HashSet(Of webpages_Roles)
    <JsonIgnore>
    Public Overridable Property Ruta As ICollection(Of Ruta) = New HashSet(Of Ruta)
    <JsonIgnore>
    Public Overridable Property Grupo As ICollection(Of Grupo) = New HashSet(Of Grupo)
    <JsonIgnore>
    Public Overridable Property CheckIn As ICollection(Of CheckIn) = New HashSet(Of CheckIn)
    <JsonIgnore>
    Public Overridable Property Conversacion As ICollection(Of Conversacion) = New HashSet(Of Conversacion)
    <JsonIgnore>
    Public Overridable Property Conversacion1 As ICollection(Of Conversacion) = New HashSet(Of Conversacion)
    <JsonIgnore>
    Public Overridable Property Mensaje As ICollection(Of Mensaje) = New HashSet(Of Mensaje)
    <JsonIgnore>
    Public Overridable Property VistaGrupo As ICollection(Of VistaGrupo) = New HashSet(Of VistaGrupo)
    <JsonIgnore>
    Public Overridable Property Conversacion2 As ICollection(Of Conversacion) = New HashSet(Of Conversacion)
    <JsonIgnore>
    Public Overridable Property FormaRespuesta As ICollection(Of FormaRespuesta) = New HashSet(Of FormaRespuesta)
    <JsonIgnore>
    Public Overridable Property CapacitacionVisitas As ICollection(Of CapacitacionVisitas) = New HashSet(Of CapacitacionVisitas)
    <JsonIgnore>
    Public Overridable Property Notificaciones As ICollection(Of Notificaciones) = New HashSet(Of Notificaciones)
    <JsonIgnore>
    Public Overridable Property UsuariosAcceso As ICollection(Of UsuariosAcceso) = New HashSet(Of UsuariosAcceso)
    <JsonIgnore>
    Public Overridable Property UsuariosAcceso1 As ICollection(Of UsuariosAcceso) = New HashSet(Of UsuariosAcceso)

End Class
