'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VistaGrupo
    Public Property idMensaje As Integer
    Public Property idUsuario As Integer
    Public Property FechaVisto As Date

    Public Overridable Property Mensaje As Mensaje
    Public Overridable Property Usuarios As Usuarios

End Class
