'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class webpages_Roles
    Public Property RoleId As Integer
    Public Property RoleName As String
    Public Property Description As String

    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)
    Public Overridable Property webpages_Acciones As ICollection(Of webpages_Acciones) = New HashSet(Of webpages_Acciones)
    Public Overridable Property webpages_RolesMain As ICollection(Of webpages_Roles) = New HashSet(Of webpages_Roles)
    Public Overridable Property webpages_RolesSub As ICollection(Of webpages_Roles) = New HashSet(Of webpages_Roles)

End Class
