'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class webpages_Membership
    Public Property UserId As Integer
    Public Property CreateDate As Nullable(Of Date)
    Public Property ConfirmationToken As String
    Public Property IsConfirmed As Nullable(Of Boolean)
    Public Property LastPasswordFailureDate As Nullable(Of Date)
    Public Property PasswordFailuresSinceLastSuccess As Integer
    Public Property Password As String
    Public Property PasswordChangedDate As Nullable(Of Date)
    Public Property PasswordSalt As String
    Public Property PasswordVerificationToken As String
    Public Property PasswordVerificationTokenExpirationDate As Nullable(Of Date)

End Class
