'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class webpages_Acciones
    Public Property idAccion As Integer
    Public Property Nombre As String

    Public Overridable Property webpages_Roles As ICollection(Of webpages_Roles) = New HashSet(Of webpages_Roles)

End Class
